server:
  port: 9001

spring:
  application:
    name: order9001

eureka:
  instance:
    instance-id: order9001 #处理在eureka中的显示
  client:
    register-with-eureka: true #注册到注册中心
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

feign:
  circuitbreaker:
    enabled: true    #开启服务降级

